### ISSUE TITLE
can't scroll iframes in iOS 5

### ISSUE THREAD

**Issue by julienw** [scottjehl/Device-Bugs#4]
I think it happened also in older iOS but in some, one could scroll using two fingers, which is not possible anymore.
## How to reproduce
1. go to a page with an iframe

**Comment by scottjehl** [comment]
Are you sure? 

I thought iframes are always sized tall enough to fit the document height in iOS? I could be wrong. 

Can you provide a test page?

**Comment by julienw** [comment]
ok, will do this during the week-end :)

**Comment by julienw** [comment]
Thanks for your comment as I didn't know this behaviour, it could help mitigate the issue.

However the issue is still there if the iframe is inside an element with "overflow: hidden" set (which is kind of logical given the behaviour you talked about). I made a testcase : http://chatillon.everlong.org/~flash/tests/ios-iframe.html

**Comment by scottjehl** [comment]
well, that's true I suppose, but I don't think it has much to do with an iframe. Any content with a set height, overflow hidden, and content that is taller than the set height will not be scrollable in iOS. This is actually true in most any browser as far as I know. Overflow scroll or auto would make it scrollable in many browsers.

That said, iOS4 does have a bug in which it requires a 2-finger scroll to scroll an element with overflow auto or scroll. This is fixed in iOS5 though. Anyway, I'm leaning towards saying this is not a bug or quirk with iframes.

We should probably file a bug here about iOS not allowing iframes to have set dimensions though. Thoughts?

**Comment by julienw** [comment]
Except that my testcase works correctly in any browser I know (including Android Browser AFAIK) except Safari Mobile :) Because the IFrame is constrained (width/height = 99%) inside the element with overflow: hidden and then gets its scrollbars... So I think it's still an issue because Safari Mobile handles this differently than any other browser ever have. Why didn't Apple fix iFrames as they fixed any other elements ?

We could file a bug as you suggest, I guess that's the same thing said differently :-)

**Comment by scottjehl** [comment]
I don't think the height: 99% is applying in iOS here, since you cannot set height on an iframe in that browser. In you're test page, we're seeing the set-height div cropping the iframe from view using overflow: hidden, but the frame itself is still there, stretched to its full height. Most other browsers will likely see the height of the iframe to fit the parent's, and the iframe's built-in scrolling will kick in.

So, yes, I agree this demo is different in iOS than other browsers, but the quirk or bug we should probably call out is that you can't constrain the size of an iframe in iOS - it'll always expand the iframe element to fit its child document.

Do you agree?

**Comment by julienw** [comment]
yep, agreed !
